### ISSUE TITLE
Error: The command "yarn run prettier:check" exited with 1.

### ISSUE THREAD

**Issue by xJuggl3r** [maxime1992/dev.to#6]
Hi

I'm using the template you provided Nothing much is changed, excepting for the info that need to be replaced. 

I'm constantly receiving the error: The command "yarn run prettier:check" exited with 1.

I tried to remove prettier with no success...
This is what I've got:
```
yarn run v1.15.2
warning package.json: No license field
error Command "test" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn test" exited with 1.
cache.2
store build cache
0.00s1.14snothing changed
Done. Your build exited with 1.
```

do you know what it might be?

**Comment by maxime1992** [comment]
:point_up: https://github.com/maxime1992/my-dev.to is my personal fork of https://github.com/maxime1992/dev.to, please report issues with the template on the latter :smiley_cat: 

(I've transferred the issue so all good for this one)

**Comment by maxime1992** [comment]
> But then I went through with pretter:base and prettier:write both worked, and then prettier:check worked afterwards.

Oh sorry, I should mention the workflow here with prettier.
The idea is that locally you should run `prettier:write` to fix the formatting in the project which is then checked automatically on CI.

If the formatting was not correct from prettier point of view it's normal that it was failing on CI :+1: 

I'll edit the readme to explain this :)

**Comment by maxime1992** [comment]
Closing as I think it's been solved. Feel free to reopen if needed :+1:
